# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('url', models.URLField(verbose_name='URL Site')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name_plural': 'Sites',
                'ordering': ['title'],
                'verbose_name': 'Site',
            },
        ),
    ]
