# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('descricao', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
    ]
